#!/usr/bin/env python3
"""Build the /photos/ gallery assets.

Reads full-resolution originals from a source directory, writes two web-sized
copies into images/photos/ and regenerates _data/photos.yml.

    python3 scripts/build_photos.py photos_src/

Source files must be named  YYYY-MM_slug.jpg  (the prefix drives the year
grouping and the sort order). Originals are never copied into the repo.

EXIF is dropped on write: phone photos carry GPS coordinates, device serials
and original timestamps, and this site is public.
"""

import argparse
import os
import re
import sys

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit("Pillow required:  pip3 install --user Pillow")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THUMB_DIR = os.path.join(REPO, "images", "photos", "thumb")
FULL_DIR = os.path.join(REPO, "images", "photos", "full")
DATA_FILE = os.path.join(REPO, "_data", "photos.yml")
CAPTION_FILE = os.path.join(REPO, "_data", "photo_captions.yml")

THUMB_WIDTH = 400          # what the wall shows
FULL_LONG_EDGE = 1600      # what the lightbox loads
NAME_RE = re.compile(r"^(\d{4})-(\d{2})_(.+)\.(jpe?g|png|webp)$", re.I)


def load_captions():
    """Minimal 'key: value' YAML reader — avoids a PyYAML dependency."""
    captions = {}
    if not os.path.exists(CAPTION_FILE):
        return captions
    for line in open(CAPTION_FILE, encoding="utf-8"):
        line = line.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip().strip('"').strip("'")
        value = value.strip().strip('"').strip("'")
        if key and value:
            captions[key] = value
    return captions


def yaml_quote(text):
    return '"%s"' % str(text).replace("\\", "\\\\").replace('"', '\\"')


def process(src_dir):
    os.makedirs(THUMB_DIR, exist_ok=True)
    os.makedirs(FULL_DIR, exist_ok=True)
    captions = load_captions()

    entries, skipped, uncaptioned = [], [], []

    for filename in sorted(os.listdir(src_dir)):
        match = NAME_RE.match(filename)
        if not match:
            if not filename.startswith("."):
                skipped.append(filename)
            continue
        year, month, slug, _ = match.groups()
        out_name = "%s-%s_%s.jpg" % (year, month, slug)

        with Image.open(os.path.join(src_dir, filename)) as raw:
            # Honour the EXIF orientation flag, then drop every metadata block:
            # copying the pixels into a fresh image leaves GPS, device serials
            # and timestamps behind.
            image = ImageOps.exif_transpose(raw).convert("RGB")
            clean = Image.new("RGB", image.size)
            clean.paste(image)

        full = clean.copy()
        full.thumbnail((FULL_LONG_EDGE, FULL_LONG_EDGE), Image.LANCZOS)
        full.save(os.path.join(FULL_DIR, out_name), "JPEG",
                  quality=86, optimize=True, progressive=True)

        thumb = clean.copy()
        thumb.thumbnail((THUMB_WIDTH, THUMB_WIDTH * 4), Image.LANCZOS)
        thumb.save(os.path.join(THUMB_DIR, out_name), "JPEG",
                   quality=82, optimize=True, progressive=True)

        caption = captions.get(out_name, "")
        if not caption:
            uncaptioned.append(out_name)

        entries.append({
            "file": out_name,
            "year": year,
            "date": "%s.%s" % (year, month),
            "width": clean.width,
            "height": clean.height,
            "caption": caption,
        })

    # Newest first.
    entries.sort(key=lambda e: e["file"], reverse=True)

    lines = [
        "# AUTO-GENERATED by scripts/build_photos.py — do not edit by hand.",
        "# Captions live in _data/photo_captions.yml.",
        "",
    ]
    for entry in entries:
        lines.append("- file: %s" % yaml_quote(entry["file"]))
        lines.append("  year: %s" % yaml_quote(entry["year"]))
        lines.append("  date: %s" % yaml_quote(entry["date"]))
        lines.append("  width: %d" % entry["width"])
        lines.append("  height: %d" % entry["height"])
        lines.append("  caption: %s" % yaml_quote(entry["caption"]))
    open(DATA_FILE, "w", encoding="utf-8").write("\n".join(lines) + "\n")

    print("%d photo(s) -> images/photos/{thumb,full}/" % len(entries))
    print("_data/photos.yml regenerated")

    stale = set(captions) - {e["file"] for e in entries}
    if skipped:
        print("\nignored (name must be YYYY-MM_slug.jpg):")
        for name in skipped:
            print("  %s" % name)
    if uncaptioned:
        print("\nno caption yet (optional, add to _data/photo_captions.yml):")
        for name in uncaptioned:
            print("  %s" % name)
    if stale:
        print("\ncaption has no matching photo — typo or deleted file:")
        for name in sorted(stale):
            print("  %s" % name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="directory holding the original photos")
    args = parser.parse_args()
    if not os.path.isdir(args.source):
        sys.exit("not a directory: %s" % args.source)
    process(args.source)


if __name__ == "__main__":
    main()
